// MoveLeads route quick facts: one short page per popular moving route,
// each linking to the full cost guide on moveleads.cloud.
//   .../exec                  -> list of all routes
//   .../exec?route=<slug>     -> one route
// ROUTES comes from Data.js (generated by build.mjs).

var SITE = 'https://moveleads.cloud';

function doGet(e) {
  var slug = e && e.parameter && e.parameter.route;
  var r = slug && ROUTES[slug];
  var page = r ? routePage_(slug, r) : indexPage_();
  return HtmlService.createHtmlOutput(page.html)
    .setTitle(page.title)
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}

function esc_(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function usd_(n) {
  return '$' + Number(n).toLocaleString('en-US');
}

function range_(row) {
  return usd_(row.low) + '–' + usd_(row.high);
}

function selfUrl_(slug) {
  return ScriptApp.getService().getUrl() + (slug ? '?route=' + encodeURIComponent(slug) : '');
}

var CSS =
  '<base target="_top"><style>' +
  'body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;color:#0f172a;margin:0;background:#f8fafc;line-height:1.6}' +
  '.w{max-width:720px;margin:0 auto;padding:28px 18px 48px}' +
  'h1{font-size:28px;line-height:1.2;margin:0 0 10px}h2{font-size:19px;margin:28px 0 10px}' +
  'p,li{font-size:16px;color:#334155}.card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:6px 16px;margin:14px 0}' +
  'table{width:100%;border-collapse:collapse}td{padding:10px 0;border-bottom:1px solid #f1f5f9}td+td{text-align:right;font-weight:700}' +
  'tr:last-child td{border-bottom:none}a{color:#ea580c;font-weight:700}' +
  '.btn{display:inline-block;background:#f97316;color:#fff;text-decoration:none;padding:12px 20px;border-radius:10px;margin:6px 8px 6px 0}' +
  '.btn.alt{background:#fff;color:#0f172a;border:1px solid #cbd5e1}.muted{font-size:13px;color:#64748b}' +
  'ul.list{padding-left:18px}' +
  '</style>';

function routePage_(slug, r) {
  var guide = SITE + '/moving/' + slug;
  var quote = SITE + '/get-quote?from=' + r.fromZip + '&to=' + r.toZip;
  var via = r.roads.length ? ' via ' + r.roads.join(' and ') : '';
  var title = r.from + ' to ' + r.to + ' Moving Cost: Quick Facts (2026)';
  var kind = r.short
    ? 'At this distance most movers charge by the hour for the crew and truck, so the size of your home and how fast the crew works set the price.'
    : (r.interstate
      ? 'Because the move crosses into ' + r.toStateName + ', it needs an interstate mover registered with the FMCSA, and the price is based mostly on the weight of your belongings and the distance.'
      : 'Long in-state moves like this one are usually priced on weight and distance rather than by the hour.');
  var tips = r.short
    ? ['Ask whether drive time between the two homes is billed, and at what rate.',
       'Have boxes packed and furniture cleared before the crew arrives; on an hourly move, waiting time costs you.']
    : ['Ask for a binding or not-to-exceed estimate in writing so the price cannot jump on delivery day.',
       'Get your delivery window in writing; on a ' + r.miles.toLocaleString('en-US') + '-mile move your belongings may arrive a few days after you do.'];
  if (r.toTax) tips.push(r.toStateName + ' has no state income tax on wages, worth factoring into your budget after the move.');

  var html = CSS + '<div class="w">' +
    '<p class="muted"><a href="' + selfUrl_() + '">All routes</a> · MoveLeads moving cost quick facts</p>' +
    '<h1>' + esc_(r.from) + ' to ' + esc_(r.to) + ': the move in numbers</h1>' +
    '<p>' + esc_(r.from + ', ' + r.fromState) + ' and ' + esc_(r.to + ', ' + r.toState) + ' are about <strong>' + r.miles.toLocaleString('en-US') + ' road miles</strong> apart, roughly ' + r.hours + ' hours behind the wheel' + esc_(via) + '. ' + esc_(kind) + '</p>' +
    '<h2>What people typically pay</h2><div class="card"><table>' +
    '<tr><td>Studio or small apartment</td><td>' + range_(r.studio) + '</td></tr>' +
    '<tr><td>2-bedroom home</td><td>' + range_(r.two) + '</td></tr>' +
    '<tr><td>' + esc_(r.four.size) + '</td><td>' + range_(r.four) + '</td></tr>' +
    '</table></div>' +
    '<p class="muted">Full-service estimates for 2026 from published industry cost data. Your quote depends on what you move, the date and extra services.</p>' +
    '<h2>Two things to sort out early</h2><ul class="list">' + tips.map(function (t) { return '<li>' + esc_(t) + '</li>'; }).join('') + '</ul>' +
    '<h2>Next step</h2>' +
    '<p>The full guide covers every home size, the drive, what changes the price and how to check a mover.</p>' +
    '<a class="btn" href="' + guide + '">Read the full ' + esc_(r.from) + ' to ' + esc_(r.to) + ' guide</a>' +
    '<a class="btn alt" href="' + quote + '">Get a free quote</a>' +
    '</div>';
  return { title: title, html: html };
}

function indexPage_() {
  var slugs = Object.keys(ROUTES);
  var items = slugs.map(function (s) {
    var r = ROUTES[s];
    return '<li><a href="' + selfUrl_(s) + '">' + esc_(r.from) + ' to ' + esc_(r.to) + '</a> · about ' + r.miles.toLocaleString('en-US') + ' miles, 2-bedroom ' + range_(r.two) + '</li>';
  }).join('');
  var html = CSS + '<div class="w">' +
    '<h1>Moving cost quick facts: ' + slugs.length + ' popular US routes</h1>' +
    '<p>Distance, drive time and typical 2026 moving costs for the routes people search most. Each page links to the full guide on <a href="' + SITE + '/moving">moveleads.cloud</a>.</p>' +
    '<ul class="list">' + items + '</ul></div>';
  return { title: 'Moving Cost Quick Facts: Popular US Routes (2026)', html: html };
}
