// Generated by build.mjs from client/src/seo/routePages.js. Do not edit.
var ROUTES = {
 "albuquerque-to-denver": {
  "from": "Albuquerque",
  "fromState": "NM",
  "fromStateName": "New Mexico",
  "to": "Denver",
  "toState": "CO",
  "toStateName": "Colorado",
  "toTax": false,
  "miles": 450,
  "hours": 8,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "87102",
  "toZip": "80202",
  "studio": {
   "size": "Studio",
   "low": 1850,
   "high": 4400
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 6500
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 6850,
   "high": 12650
  }
 },
 "st-louis-to-chicago": {
  "from": "St. Louis",
  "fromState": "MO",
  "fromStateName": "Missouri",
  "to": "Chicago",
  "toState": "IL",
  "toStateName": "Illinois",
  "toTax": false,
  "miles": 295,
  "hours": 6,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "63101",
  "toZip": "60601",
  "studio": {
   "size": "Studio",
   "low": 1800,
   "high": 4300
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 6500
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 6800,
   "high": 12500
  }
 },
 "san-antonio-to-houston": {
  "from": "San Antonio",
  "fromState": "TX",
  "fromStateName": "Texas",
  "to": "Houston",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 195,
  "hours": 4,
  "short": true,
  "interstate": false,
  "roads": [],
  "fromZip": "78205",
  "toZip": "77002",
  "studio": {
   "size": "Studio",
   "crew": "2 movers",
   "hours": "3–5",
   "low": 550,
   "high": 1100
  },
  "two": {
   "size": "2 bedrooms",
   "crew": "3 movers",
   "hours": "5–7",
   "low": 950,
   "high": 1900
  },
  "four": {
   "size": "4+ bedrooms",
   "crew": "4–5 movers",
   "hours": "9–12",
   "low": 1800,
   "high": 3950
  }
 },
 "san-antonio-to-austin": {
  "from": "San Antonio",
  "fromState": "TX",
  "fromStateName": "Texas",
  "to": "Austin",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 80,
  "hours": 2,
  "short": true,
  "interstate": false,
  "roads": [],
  "fromZip": "78205",
  "toZip": "78701",
  "studio": {
   "size": "Studio",
   "crew": "2 movers",
   "hours": "3–5",
   "low": 400,
   "high": 850
  },
  "two": {
   "size": "2 bedrooms",
   "crew": "3 movers",
   "hours": "5–7",
   "low": 750,
   "high": 1600
  },
  "four": {
   "size": "4+ bedrooms",
   "crew": "4–5 movers",
   "hours": "9–12",
   "low": 1550,
   "high": 3500
  }
 },
 "dallas-to-austin": {
  "from": "Dallas",
  "fromState": "TX",
  "fromStateName": "Texas",
  "to": "Austin",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 195,
  "hours": 3,
  "short": true,
  "interstate": false,
  "roads": [],
  "fromZip": "75201",
  "toZip": "78701",
  "studio": {
   "size": "Studio",
   "crew": "2 movers",
   "hours": "3–5",
   "low": 500,
   "high": 950
  },
  "two": {
   "size": "2 bedrooms",
   "crew": "3 movers",
   "hours": "5–7",
   "low": 850,
   "high": 1750
  },
  "four": {
   "size": "4+ bedrooms",
   "crew": "4–5 movers",
   "hours": "9–12",
   "low": 1700,
   "high": 3700
  }
 },
 "austin-to-dallas": {
  "from": "Austin",
  "fromState": "TX",
  "fromStateName": "Texas",
  "to": "Dallas",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 195,
  "hours": 3,
  "short": true,
  "interstate": false,
  "roads": [],
  "fromZip": "78701",
  "toZip": "75201",
  "studio": {
   "size": "Studio",
   "crew": "2 movers",
   "hours": "3–5",
   "low": 500,
   "high": 950
  },
  "two": {
   "size": "2 bedrooms",
   "crew": "3 movers",
   "hours": "5–7",
   "low": 850,
   "high": 1750
  },
  "four": {
   "size": "4+ bedrooms",
   "crew": "4–5 movers",
   "hours": "9–12",
   "low": 1700,
   "high": 3700
  }
 },
 "houston-to-dallas": {
  "from": "Houston",
  "fromState": "TX",
  "fromStateName": "Texas",
  "to": "Dallas",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 240,
  "hours": 4,
  "short": true,
  "interstate": false,
  "roads": [],
  "fromZip": "77002",
  "toZip": "75201",
  "studio": {
   "size": "Studio",
   "crew": "2 movers",
   "hours": "3–5",
   "low": 550,
   "high": 1100
  },
  "two": {
   "size": "2 bedrooms",
   "crew": "3 movers",
   "hours": "5–7",
   "low": 950,
   "high": 1900
  },
  "four": {
   "size": "4+ bedrooms",
   "crew": "4–5 movers",
   "hours": "9–12",
   "low": 1800,
   "high": 3950
  }
 },
 "boston-to-los-angeles": {
  "from": "Boston",
  "fromState": "MA",
  "fromStateName": "Massachusetts",
  "to": "Los Angeles",
  "toState": "CA",
  "toStateName": "California",
  "toTax": false,
  "miles": 2995,
  "hours": 54,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "02108",
  "toZip": "90012",
  "studio": {
   "size": "Studio",
   "low": 3100,
   "high": 7000
  },
  "two": {
   "size": "2 bedrooms",
   "low": 4500,
   "high": 10900
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 9500,
   "high": 16900
  }
 },
 "san-diego-to-boston": {
  "from": "San Diego",
  "fromState": "CA",
  "fromStateName": "California",
  "to": "Boston",
  "toState": "MA",
  "toStateName": "Massachusetts",
  "toTax": false,
  "miles": 3030,
  "hours": 55,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "92101",
  "toZip": "02108",
  "studio": {
   "size": "Studio",
   "low": 3100,
   "high": 7000
  },
  "two": {
   "size": "2 bedrooms",
   "low": 4500,
   "high": 10900
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 9500,
   "high": 16900
  }
 },
 "denver-to-las-vegas": {
  "from": "Denver",
  "fromState": "CO",
  "fromStateName": "Colorado",
  "to": "Las Vegas",
  "toState": "NV",
  "toStateName": "Nevada",
  "toTax": true,
  "miles": 750,
  "hours": 13,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "80202",
  "toZip": "89101",
  "studio": {
   "size": "Studio",
   "low": 2100,
   "high": 4950
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 6500
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7150,
   "high": 13300
  }
 },
 "sioux-falls-to-denver": {
  "from": "Sioux Falls",
  "fromState": "SD",
  "fromStateName": "South Dakota",
  "to": "Denver",
  "toState": "CO",
  "toStateName": "Colorado",
  "toTax": false,
  "miles": 620,
  "hours": 12,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "57104",
  "toZip": "80202",
  "studio": {
   "size": "Studio",
   "low": 2000,
   "high": 4750
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 6500
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7050,
   "high": 13000
  }
 },
 "phoenix-to-san-diego": {
  "from": "Phoenix",
  "fromState": "AZ",
  "fromStateName": "Arizona",
  "to": "San Diego",
  "toState": "CA",
  "toStateName": "California",
  "toTax": false,
  "miles": 355,
  "hours": 7,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "85004",
  "toZip": "92101",
  "studio": {
   "size": "Studio",
   "low": 1800,
   "high": 4300
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 6500
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 6800,
   "high": 12500
  }
 },
 "houston-to-austin": {
  "from": "Houston",
  "fromState": "TX",
  "fromStateName": "Texas",
  "to": "Austin",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 165,
  "hours": 3,
  "short": true,
  "interstate": false,
  "roads": [],
  "fromZip": "77002",
  "toZip": "78701",
  "studio": {
   "size": "Studio",
   "crew": "2 movers",
   "hours": "3–5",
   "low": 500,
   "high": 950
  },
  "two": {
   "size": "2 bedrooms",
   "crew": "3 movers",
   "hours": "5–7",
   "low": 850,
   "high": 1750
  },
  "four": {
   "size": "4+ bedrooms",
   "crew": "4–5 movers",
   "hours": "9–12",
   "low": 1700,
   "high": 3700
  }
 },
 "el-paso-to-austin": {
  "from": "El Paso",
  "fromState": "TX",
  "fromStateName": "Texas",
  "to": "Austin",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 575,
  "hours": 10,
  "short": false,
  "interstate": false,
  "roads": [],
  "fromZip": "79901",
  "toZip": "78701",
  "studio": {
   "size": "Studio",
   "low": 1950,
   "high": 4650
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 6500
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7000,
   "high": 12900
  }
 },
 "fort-worth-to-austin": {
  "from": "Fort Worth",
  "fromState": "TX",
  "fromStateName": "Texas",
  "to": "Austin",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 190,
  "hours": 3,
  "short": true,
  "interstate": false,
  "roads": [],
  "fromZip": "76102",
  "toZip": "78701",
  "studio": {
   "size": "Studio",
   "crew": "2 movers",
   "hours": "3–5",
   "low": 500,
   "high": 950
  },
  "two": {
   "size": "2 bedrooms",
   "crew": "3 movers",
   "hours": "5–7",
   "low": 850,
   "high": 1750
  },
  "four": {
   "size": "4+ bedrooms",
   "crew": "4–5 movers",
   "hours": "9–12",
   "low": 1700,
   "high": 3700
  }
 },
 "boston-to-nashville": {
  "from": "Boston",
  "fromState": "MA",
  "fromStateName": "Massachusetts",
  "to": "Nashville",
  "toState": "TN",
  "toStateName": "Tennessee",
  "toTax": true,
  "miles": 1095,
  "hours": 21,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "02108",
  "toZip": "37203",
  "studio": {
   "size": "Studio",
   "low": 2350,
   "high": 5450
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 7400
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7400,
   "high": 13850
  }
 },
 "kansas-city-to-st-louis": {
  "from": "Kansas City",
  "fromState": "MO",
  "fromStateName": "Missouri",
  "to": "St. Louis",
  "toState": "MO",
  "toStateName": "Missouri",
  "toTax": false,
  "miles": 250,
  "hours": 5,
  "short": false,
  "interstate": false,
  "roads": [],
  "fromZip": "64106",
  "toZip": "63101",
  "studio": {
   "size": "Studio",
   "low": 1800,
   "high": 4300
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 6500
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 6800,
   "high": 12500
  }
 },
 "boston-to-miami": {
  "from": "Boston",
  "fromState": "MA",
  "fromStateName": "Massachusetts",
  "to": "Miami",
  "toState": "FL",
  "toStateName": "Florida",
  "toTax": true,
  "miles": 1490,
  "hours": 29,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "02108",
  "toZip": "33130",
  "studio": {
   "size": "Studio",
   "low": 2550,
   "high": 5850
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3500,
   "high": 8800
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7650,
   "high": 14350
  }
 },
 "los-angeles-to-portland": {
  "from": "Los Angeles",
  "fromState": "CA",
  "fromStateName": "California",
  "to": "Portland",
  "toState": "OR",
  "toStateName": "Oregon",
  "toTax": false,
  "miles": 960,
  "hours": 18,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "90012",
  "toZip": "97204",
  "studio": {
   "size": "Studio",
   "low": 2250,
   "high": 5250
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 7050
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7300,
   "high": 13600
  }
 },
 "kansas-city-to-denver": {
  "from": "Kansas City",
  "fromState": "MO",
  "fromStateName": "Missouri",
  "to": "Denver",
  "toState": "CO",
  "toStateName": "Colorado",
  "toTax": false,
  "miles": 605,
  "hours": 10,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "64106",
  "toZip": "80202",
  "studio": {
   "size": "Studio",
   "low": 2000,
   "high": 4700
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 6500
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7000,
   "high": 13000
  }
 },
 "greenville-to-charleston": {
  "from": "Greenville",
  "fromState": "SC",
  "fromStateName": "South Carolina",
  "to": "Charleston",
  "toState": "SC",
  "toStateName": "South Carolina",
  "toTax": false,
  "miles": 215,
  "hours": 4,
  "short": true,
  "interstate": false,
  "roads": [],
  "fromZip": "29601",
  "toZip": "29401",
  "studio": {
   "size": "Studio",
   "crew": "2 movers",
   "hours": "3–5",
   "low": 550,
   "high": 1100
  },
  "two": {
   "size": "2 bedrooms",
   "crew": "3 movers",
   "hours": "5–7",
   "low": 950,
   "high": 1900
  },
  "four": {
   "size": "4+ bedrooms",
   "crew": "4–5 movers",
   "hours": "9–12",
   "low": 1800,
   "high": 3950
  }
 },
 "boston-to-houston": {
  "from": "Boston",
  "fromState": "MA",
  "fromStateName": "Massachusetts",
  "to": "Houston",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 1840,
  "hours": 35,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "02108",
  "toZip": "77002",
  "studio": {
   "size": "Studio",
   "low": 2700,
   "high": 6150
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3750,
   "high": 10250
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7800,
   "high": 14700
  }
 },
 "los-angeles-to-miami": {
  "from": "Los Angeles",
  "fromState": "CA",
  "fromStateName": "California",
  "to": "Miami",
  "toState": "FL",
  "toStateName": "Florida",
  "toTax": true,
  "miles": 2735,
  "hours": 48,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "90012",
  "toZip": "33130",
  "studio": {
   "size": "Studio",
   "low": 3000,
   "high": 6800
  },
  "two": {
   "size": "2 bedrooms",
   "low": 4350,
   "high": 10900
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 9050,
   "high": 16350
  }
 },
 "dallas-to-houston": {
  "from": "Dallas",
  "fromState": "TX",
  "fromStateName": "Texas",
  "to": "Houston",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 240,
  "hours": 4,
  "short": true,
  "interstate": false,
  "roads": [],
  "fromZip": "75201",
  "toZip": "77002",
  "studio": {
   "size": "Studio",
   "crew": "2 movers",
   "hours": "3–5",
   "low": 550,
   "high": 1100
  },
  "two": {
   "size": "2 bedrooms",
   "crew": "3 movers",
   "hours": "5–7",
   "low": 950,
   "high": 1900
  },
  "four": {
   "size": "4+ bedrooms",
   "crew": "4–5 movers",
   "hours": "9–12",
   "low": 1800,
   "high": 3950
  }
 },
 "atlanta-to-louisville": {
  "from": "Atlanta",
  "fromState": "GA",
  "fromStateName": "Georgia",
  "to": "Louisville",
  "toState": "KY",
  "toStateName": "Kentucky",
  "toTax": false,
  "miles": 390,
  "hours": 8,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "30303",
  "toZip": "40202",
  "studio": {
   "size": "Studio",
   "low": 1800,
   "high": 4300
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 6500
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 6800,
   "high": 12500
  }
 },
 "los-angeles-to-las-vegas": {
  "from": "Los Angeles",
  "fromState": "CA",
  "fromStateName": "California",
  "to": "Las Vegas",
  "toState": "NV",
  "toStateName": "Nevada",
  "toTax": true,
  "miles": 270,
  "hours": 5,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "90012",
  "toZip": "89101",
  "studio": {
   "size": "Studio",
   "low": 1800,
   "high": 4300
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 6500
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 6800,
   "high": 12500
  }
 },
 "austin-to-houston": {
  "from": "Austin",
  "fromState": "TX",
  "fromStateName": "Texas",
  "to": "Houston",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 165,
  "hours": 3,
  "short": true,
  "interstate": false,
  "roads": [],
  "fromZip": "78701",
  "toZip": "77002",
  "studio": {
   "size": "Studio",
   "crew": "2 movers",
   "hours": "3–5",
   "low": 500,
   "high": 950
  },
  "two": {
   "size": "2 bedrooms",
   "crew": "3 movers",
   "hours": "5–7",
   "low": 850,
   "high": 1750
  },
  "four": {
   "size": "4+ bedrooms",
   "crew": "4–5 movers",
   "hours": "9–12",
   "low": 1700,
   "high": 3700
  }
 },
 "sacramento-to-san-francisco": {
  "from": "Sacramento",
  "fromState": "CA",
  "fromStateName": "California",
  "to": "San Francisco",
  "toState": "CA",
  "toStateName": "California",
  "toTax": false,
  "miles": 85,
  "hours": 2,
  "short": true,
  "interstate": false,
  "roads": [],
  "fromZip": "95814",
  "toZip": "94103",
  "studio": {
   "size": "Studio",
   "crew": "2 movers",
   "hours": "3–5",
   "low": 400,
   "high": 850
  },
  "two": {
   "size": "2 bedrooms",
   "crew": "3 movers",
   "hours": "5–7",
   "low": 750,
   "high": 1600
  },
  "four": {
   "size": "4+ bedrooms",
   "crew": "4–5 movers",
   "hours": "9–12",
   "low": 1550,
   "high": 3500
  }
 },
 "los-angeles-to-san-diego": {
  "from": "Los Angeles",
  "fromState": "CA",
  "fromStateName": "California",
  "to": "San Diego",
  "toState": "CA",
  "toStateName": "California",
  "toTax": false,
  "miles": 120,
  "hours": 2,
  "short": true,
  "interstate": false,
  "roads": [],
  "fromZip": "90012",
  "toZip": "92101",
  "studio": {
   "size": "Studio",
   "crew": "2 movers",
   "hours": "3–5",
   "low": 400,
   "high": 850
  },
  "two": {
   "size": "2 bedrooms",
   "crew": "3 movers",
   "hours": "5–7",
   "low": 750,
   "high": 1600
  },
  "four": {
   "size": "4+ bedrooms",
   "crew": "4–5 movers",
   "hours": "9–12",
   "low": 1550,
   "high": 3500
  }
 },
 "seattle-to-houston": {
  "from": "Seattle",
  "fromState": "WA",
  "fromStateName": "Washington",
  "to": "Houston",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 2320,
  "hours": 41,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "98101",
  "toZip": "77002",
  "studio": {
   "size": "Studio",
   "low": 2850,
   "high": 6550
  },
  "two": {
   "size": "2 bedrooms",
   "low": 4100,
   "high": 10900
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 8400,
   "high": 15550
  }
 },
 "charlotte-to-austin": {
  "from": "Charlotte",
  "fromState": "NC",
  "fromStateName": "North Carolina",
  "to": "Austin",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 1165,
  "hours": 22,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "28202",
  "toZip": "78701",
  "studio": {
   "size": "Studio",
   "low": 2400,
   "high": 5500
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 7550
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7450,
   "high": 13950
  }
 },
 "miami-to-charlotte": {
  "from": "Miami",
  "fromState": "FL",
  "fromStateName": "Florida",
  "to": "Charlotte",
  "toState": "NC",
  "toStateName": "North Carolina",
  "toTax": false,
  "miles": 725,
  "hours": 13,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "33130",
  "toZip": "28202",
  "studio": {
   "size": "Studio",
   "low": 2100,
   "high": 4900
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 6500
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7150,
   "high": 13250
  }
 },
 "philadelphia-to-houston": {
  "from": "Philadelphia",
  "fromState": "PA",
  "fromStateName": "Pennsylvania",
  "to": "Houston",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 1545,
  "hours": 29,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "19103",
  "toZip": "77002",
  "studio": {
   "size": "Studio",
   "low": 2550,
   "high": 5900
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3500,
   "high": 9000
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7650,
   "high": 14400
  }
 },
 "houston-to-charlotte": {
  "from": "Houston",
  "fromState": "TX",
  "fromStateName": "Texas",
  "to": "Charlotte",
  "toState": "NC",
  "toStateName": "North Carolina",
  "toTax": false,
  "miles": 1035,
  "hours": 19,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "77002",
  "toZip": "28202",
  "studio": {
   "size": "Studio",
   "low": 2300,
   "high": 5350
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 7250
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7350,
   "high": 13750
  }
 },
 "san-diego-to-los-angeles": {
  "from": "San Diego",
  "fromState": "CA",
  "fromStateName": "California",
  "to": "Los Angeles",
  "toState": "CA",
  "toStateName": "California",
  "toTax": false,
  "miles": 120,
  "hours": 2,
  "short": true,
  "interstate": false,
  "roads": [],
  "fromZip": "92101",
  "toZip": "90012",
  "studio": {
   "size": "Studio",
   "crew": "2 movers",
   "hours": "3–5",
   "low": 400,
   "high": 850
  },
  "two": {
   "size": "2 bedrooms",
   "crew": "3 movers",
   "hours": "5–7",
   "low": 750,
   "high": 1600
  },
  "four": {
   "size": "4+ bedrooms",
   "crew": "4–5 movers",
   "hours": "9–12",
   "low": 1550,
   "high": 3500
  }
 },
 "houston-to-el-paso": {
  "from": "Houston",
  "fromState": "TX",
  "fromStateName": "Texas",
  "to": "El Paso",
  "toState": "TX",
  "toStateName": "Texas",
  "toTax": true,
  "miles": 745,
  "hours": 12,
  "short": false,
  "interstate": false,
  "roads": [],
  "fromZip": "77002",
  "toZip": "79901",
  "studio": {
   "size": "Studio",
   "low": 2100,
   "high": 4950
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 6500
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7150,
   "high": 13250
  }
 },
 "houston-to-orlando": {
  "from": "Houston",
  "fromState": "TX",
  "fromStateName": "Texas",
  "to": "Orlando",
  "toState": "FL",
  "toStateName": "Florida",
  "toTax": true,
  "miles": 965,
  "hours": 18,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "77002",
  "toZip": "32801",
  "studio": {
   "size": "Studio",
   "low": 2250,
   "high": 5250
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 7050
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7300,
   "high": 13650
  }
 },
 "los-angeles-to-phoenix": {
  "from": "Los Angeles",
  "fromState": "CA",
  "fromStateName": "California",
  "to": "Phoenix",
  "toState": "AZ",
  "toStateName": "Arizona",
  "toTax": false,
  "miles": 375,
  "hours": 7,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "90012",
  "toZip": "85004",
  "studio": {
   "size": "Studio",
   "low": 1800,
   "high": 4300
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 6500
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 6800,
   "high": 12500
  }
 },
 "san-diego-to-phoenix": {
  "from": "San Diego",
  "fromState": "CA",
  "fromStateName": "California",
  "to": "Phoenix",
  "toState": "AZ",
  "toStateName": "Arizona",
  "toTax": false,
  "miles": 355,
  "hours": 7,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "92101",
  "toZip": "85004",
  "studio": {
   "size": "Studio",
   "low": 1800,
   "high": 4300
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3300,
   "high": 6500
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 6800,
   "high": 12500
  }
 },
 "boston-to-denver": {
  "from": "Boston",
  "fromState": "MA",
  "fromStateName": "Massachusetts",
  "to": "Denver",
  "toState": "CO",
  "toStateName": "Colorado",
  "toTax": false,
  "miles": 1980,
  "hours": 36,
  "short": false,
  "interstate": true,
  "roads": [],
  "fromZip": "02108",
  "toZip": "80202",
  "studio": {
   "size": "Studio",
   "low": 2750,
   "high": 6300
  },
  "two": {
   "size": "2 bedrooms",
   "low": 3850,
   "high": 10800
  },
  "four": {
   "size": "4+ bedrooms",
   "low": 7900,
   "high": 14850
  }
 }
};
