// Builds the "MoveLeads route quick facts" Apps Script web app from the
// site's own route data. Each page is a short, distinct summary (distance,
// drive, typical cost, two tips) that links to the full guide on
// moveleads.cloud. It deliberately does not copy the site's page text.
//
//   node apps-script/route-guides/build.mjs   -> writes src/Data.js
//   cd apps-script/route-guides && clasp push && clasp redeploy <id>
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ROUTE_PAGES, routeCostRows, STATE_NAMES } from '../../client/src/seo/routePages.js';
import { ROUTE_HIGHWAYS } from '../../client/src/seo/routeHighways.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CSV = process.env.SEMRUSH_CSV;

// Top 40 served routes by search demand (Semrush, moveBuddha popular-routes
// export, Oct 2026). Jacksonville to Orlando is left out: its searches are
// travel queries (Oct 6 audit). Falls back to the saved list without the CSV.
const SAVED = JSON.parse(fs.readFileSync(path.join(HERE, 'routes.json'), 'utf8'));
let slugs = SAVED;
if (CSV) {
  const demand = {};
  for (const line of fs.readFileSync(CSV, 'utf8').trim().split('\n').slice(1)) {
    const c = line.split(',');
    const m = c[6]?.match(/\/([a-z-]+-to-[a-z-]+)\/$/);
    if (m && ROUTE_PAGES[m[1]] && m[1] !== 'jacksonville-to-orlando') demand[m[1]] = (demand[m[1]] || 0) + Number(c[3]);
  }
  slugs = Object.entries(demand).sort((a, b) => b[1] - a[1]).slice(0, 40).map(([s]) => s);
  fs.writeFileSync(path.join(HERE, 'routes.json'), JSON.stringify(slugs, null, 2) + '\n');
}

const pick = (rows, size) => rows.find((r) => r.size === size);
const data = {};
for (const slug of slugs) {
  const r = ROUTE_PAGES[slug];
  if (!r) throw new Error(`unknown route ${slug}`);
  const rows = routeCostRows(r);
  const roads = (ROUTE_HIGHWAYS[slug] || []).filter((x) => /^(I|US)-\d/.test(x)).slice(0, 2);
  data[slug] = {
    from: r.from.name, fromState: r.from.state, fromStateName: STATE_NAMES[r.from.state],
    to: r.to.name, toState: r.to.state, toStateName: STATE_NAMES[r.to.state],
    toTax: !!r.to.tax, miles: r.miles, hours: r.hours, short: !!r.short,
    interstate: r.from.state !== r.to.state, roads,
    fromZip: r.from.zip, toZip: r.to.zip,
    studio: pick(rows, 'Studio'), two: pick(rows, '2 bedrooms'), four: rows[rows.length - 1],
  };
}
fs.writeFileSync(
  path.join(HERE, 'src', 'Data.js'),
  `// Generated by build.mjs from client/src/seo/routePages.js. Do not edit.\nvar ROUTES = ${JSON.stringify(data, null, 1)};\n`,
);
console.log(`Data.js: ${Object.keys(data).length} routes`);
